### ISSUE TITLE
Selects white text on light gray background

### ISSUE THREAD

**Issue by ilaskaev** [growthbunker/vuedarkmode#22]
As shown in the image below.

https://puu.sh/BUuaO/e3799d0f5d.png

Running Windows 10 on Chrome 70.

**Comment by LeCoupa** [comment]
Thank you for the details, I'll fix this. 👍

**Comment by aloisdg** [comment]
small tip, this is how to display a picture in markdown:`![alt text](https://puu.sh/BUuaO/e3799d0f5d.png)`

![screenshot of select bug](https://puu.sh/BUuaO/e3799d0f5d.png)

**Comment by LeCoupa** [comment]
I just merged the PR above. I will publish the changes to NPM in the coming days.

**Comment by ilaskaev** [comment]
All fixed for me thank you.
