### ISSUE TITLE
Form items need focus styles for keyboard navigation

### ISSUE THREAD

**Issue by luminarious** [growthbunker/vuedarkmode#23]
Input, textarea and select have focus style.
Checkbox, radio and switch don't show which one I am toggling.

**Comment by LeCoupa** [comment]
Thank you, I'll fix that for these elements. 👍

**Comment by LeCoupa** [comment]
I just fixed this in https://github.com/LeCoupa/vuedarkmode/commit/039ae41176493f1814b30755b4ea9c8e826e3657

Thanks!
