### ISSUE TITLE
[Feature request] Copy icons to clipboard on click

### ISSUE THREAD

**Issue by guastallaigor** [growthbunker/vuedarkmode#30]
### What problem does this feature solve?

Basically I think it would be nice to click an icon and have the icon name copied to clipboard inside the docs `#baseIcon`.

### What is your proposed solution?

The only way I know how to do with plain JS it's to add an `@click` that calls a method inside the `GuideBaseIcons.vue`, create a temporarily `textarea` element, copy the icon's name to that `textarea`, exec the copy command and remove the `textarea`.

------------------------------
**Note:** If you want this feature request I the code for this, and I can make a PR for you to see.

**Comment by LeCoupa** [comment]
That's a good idea. I think we should use this:

https://www.npmjs.com/package/vue-clipboard2
