### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by Nisthar** [growthbunker/vuedarkmode#37]
![untitled](https://user-images.githubusercontent.com/11994157/53076545-e4292d80-3515-11e9-9315-7f1715ee2201.png)

```js
 <dm-input
        v-model="instaId"
        placeholder="Enter your instagram id"
        validation="{ required: true, regex: /\\.(js|ts)$/ }"
        name="instaId"
        left-icon="alternate_email"
      ></dm-input>
```

**Comment by LeCoupa** [comment]
Thank you I'll look into this ASAP. Does it work if you bind the validation prop like below?

```html
 <dm-input
        v-model="instaId"
        :validation="{ required: true, regex: /\\.(js|ts)$/ }"
        placeholder="Enter your instagram id"
        name="instaId"
        left-icon="alternate_email"
></dm-input>
```

**Comment by Nisthar** [comment]
@LeCoupa It seems to work. But i am still getting this error

![untitled](https://user-images.githubusercontent.com/11994157/53077306-b9d86f80-3517-11e9-8c25-dc16af5a8ff7.png)

**Comment by Nisthar** [comment]
Its working now despite the warning

**Comment by LeCoupa** [comment]
Great, I'm fixing the warning. Should be live in a few minutes.

**Comment by LeCoupa** [comment]
Try to update vuedarkmode to `0.3.23`. :) 

And thank you for reporting this issue!

**Comment by Nisthar** [comment]
@LeCoupa Thanks 👍

**Comment by ifkas** [comment]
Hello, is vee validate included or need to be installed separately?

**Comment by LeCoupa** [comment]
Hello @ifkas. It is included. :)

https://github.com/LeCoupa/vuedarkmode/blob/master/lib/package.json#L34
