### ISSUE TITLE
dm-checkbox  full-width="false" Invalid prop

### ISSUE THREAD

**Issue by hcen1997** [growthbunker/vuedarkmode#40]
[Vue warn]: Invalid prop: type check failed for prop "fullWidth". Expected Boolean, got String with value "false".

**Comment by hcen1997** [comment]
"dependencies": {
    "bootstrap": "^4.3.1",
    "core-js": "^2.6.5",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuedarkmode": "^0.3.23"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.7.0",
    "@vue/cli-plugin-eslint": "^3.7.0",
    "@vue/cli-service": "^3.7.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-template-compiler": "^2.5.21"
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}

**Comment by LeCoupa** [comment]
Hello, you probably forgot to bind the prop. Use :full-width="true"

**Comment by hcen1997** [comment]
![image](https://user-images.githubusercontent.com/22320578/57347655-9ec7e400-7185-11e9-8109-9494ca27c61d.png)
![image](https://user-images.githubusercontent.com/22320578/57347680-b3a47780-7185-11e9-9644-ec2dc389eb79.png)
\<dm-heading tag="h2" name="timmer" :full-width="false">Timmer\</dm-heading>
\<dm-button class="ansBtn">Hint\</dm-button>
I just want this two items in the same line...

**Comment by hcen1997** [comment]
finally i figure out ...
dm-cleckbox'props full-width work fine by using \':full-width="false"'.
dm-heading dont have props named 'full-width'

thanks for build this awesome design. ~_~

**Comment by LeCoupa** [comment]
You're welcome!
