### ISSUE TITLE
Add ability for checkboxes to be used with arrays

### ISSUE THREAD

**Issue by SageStarCodes** [growthbunker/vuedarkmode#47]
Currently the checkbox component does not work as expected. Normally the input element of type checkbox can work with arrays referenced in v-model by adding and removing its value from the array, gb-checkbox just coerces whatever is in the value property to a boolean by using the `!` operator and following that, it overwrites the array.

**Comment by LeCoupa** [comment]
I don't understand what you are trying to do. Normally, a checkbox should return a Boolean value (true when checked, false when unchecked).

Do you have an example in mind?

**Comment by SageStarCodes** [comment]
Yes, I do, I would like to be able to use the checkboxes as shown in the example in Vue.js documentation: https://vuejs.org/v2/guide/forms.html#Checkbox

**Comment by LeCoupa** [comment]
I see it now. Thank you. Unfortunately, I do not plan on adding this behavior as you could use the field-toggle to get the same.
