### ISSUE TITLE
nothing changes

### ISSUE THREAD

**Issue by robertnicjoo** [growthbunker/vuedarkmode#49]
I'm not sure if i did anything wrong or not but nothing changes with switch button.

# Code

`app.js`

```js
require('./bootstrap');
window.Vue = require('vue');
import VueDarkMode from "@growthbunker/vuedarkmode";
Vue.use(VueDarkMode);

import VueAxios from 'vue-axios';
import axios from 'axios';
Vue.use(VueAxios, axios);

import App from "./components/App";
import router from './router.js';

const app = new Vue({
    el: '#app',
    router,
    render: (h) => h(App)
});
```

`App.vue` My main component(all routes open in here)

```js
<template>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <router-link to="/" class="nav-link">Home</router-link>
            </li>
            <li class="nav-item">
                <router-link :to="{name: 'about'}" class="nav-link">About</router-link>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <gb-toggle theme="dark" />
            </li>
        </ul>
        </nav><br />
        <div>
            <transition name="fade">
                <router-view></router-view>
            </transition>
        </div>
    </div>
</template>

<style>
    .fade-enter-active, .fade-leave-active {
      transition: opacity .5s
    }
    .fade-enter, .fade-leave-active {
      opacity: 0
    }
</style>

<script>
    export default {
        mounted() {
            // console.log('Component mounted.')
        }
    }
</script>
```
**Any idea?**

**Comment by robertnicjoo** [comment]
no one?

**Comment by LeCoupa** [comment]
Sorry for the late reply. Can you try to add a `v-model` to `gb-toggle` and see if that is working on your side?

This is not required though. Can you send me a video to see what is not changing? We are using Vue Dark Mode in production on Growth Bunker and things are working fine for us.

**Comment by robertnicjoo** [comment]
hi, thanks for the reply, would you mind show me example of v-model? not sure what i should to add.

ps: I'm using vue and this packge in laravel application.

**Comment by LeCoupa** [comment]
Use it like this:

```javascript
<template>
  <gb-toggle v-model="myValue" />
</template>

<script>
export default {
  data: () => ({
    myValue: true
  })
}
</script>

```

**Comment by robertnicjoo** [comment]
@LeCoupa So I added `v-model` just like you showed me and no difference here is small video as you requested

https://www.loom.com/share/90994025ced84329b94bd79c1f0599ef

**Comment by LeCoupa** [comment]
Sorry but I don't get what you are trying to do. Please, be more explicit.

**Comment by robertnicjoo** [comment]
ok, I'm trying to get dark mode with switch button.
getting dark background, light content fonts etc. switch between light and dark mode.

**Comment by LeCoupa** [comment]
Vue Dark Mode is a library with essential components available in dark/light. It does not include these features. If you want to toggle dark/mode automatically, you can use this:

https://darkmodejs.learn.uno/

**Comment by DenisFerrero** [comment]
Hi, can you provide an example of the integration of darkmodejs and vuedarkmode? I'm looking to bind them together but without success, even if I change the $gb.vuedarkmode.theme property manually the computed is not triggered and all the components still remain the same
